name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'  # Set the R version here

      - name: Install TTR manually
        run: |
          install.packages("TTR", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Install dependencies
        run: 
          Rscript -e 'install.packages("remotes"); remotes::install_deps(dependencies = TRUE)'
        
      - name: Run R CMD check
        run: R CMD check .
